### PR TITLE
AMD64_MINGW m3_link fix by calling subst_chars()

### PR DESCRIPTION
**Pull request by VictorMiasnikov**
Allow use boot2min.py and boot2.py with target boot2.py

### CODE REVIEW

**Comment by jaykrell** [comment]
Hm. Are you sure this is needed? 
Where are the backward slashes coming from?
Is this an alternative to my changes?
Maybe this is preferable?

**Comment by VictorMiasnikov** [comment]
Are you sure this is needed?Today - yes, it is Where are the backward slashes coming from? YesIs this an alternative to my changes?  No, it is additionMaybe this is preferable?06.07.2021, 21:11, "Jay Krell" ***@***.***>:
Hm. Are you sure this is needed?
Where are the backward slashes coming from?
Is this an alternative to my changes?
Maybe this is preferable?

**Comment by VictorMiasnikov** [comment]
Thanks!06.07.2021, 21:12, "Jay Krell" ***@***.***>:
Merged #722 into master.

**Comment by VictorMiasnikov** [comment]
> J.K.} Maybe this is preferable?

 I am not sure: 
I more like when fixes ( will be made) by changes in .m3 / .i3 files

**Pull request merged**
