### PR TITLE
Skip all the calltech-parser, caltech-other, scheme stuff on windows

### PR DESCRIPTION
**Pull request by jaykrell**
since it does not in general build.

There is accidental newline format change in some of them, sorry.

### CODE REVIEW

**Comment by mikanystrom** [comment]
Ah did I break everything? What goes wrong? I think it all builds fine on
AMD64_LINUX ... I think....

**Comment by jaykrell** [comment]
Lots of code in there that doesn't compile on Windows.

tm->gmtoff
diskavail
at least.
I think more.
I gave up for now.

https://github.com/modula3/cm3/pull/49 is  a start but I didn't test it, and it didn't suffice.


 - Jay

________________________________

**Comment by VictorMiasnikov** [comment]
I.e. then I run

python upgrade.py && python do-cm3-all.py realclean skipgcc && python do-cm3-all.py buildship

 with
CM3_TARGET=AMD64_NT

and files:

kext.exe
kyacc.exe
klex.exe
ktok.exe
kyacclib.dll
klexlib.dll
ktoklib.dll
m3browserhack.exe
kgv.exe
dcpane.dll
drawcontext.dll
kemacs.exe
paneman.dll
cit_util.dll
m3tmplhack.exe
cit_common.dll
m3X11R4.dll

don't updated ... 

It related with #50?

**Comment by jaykrell** [comment]
That is expected now. One of those is X Windows, and all the rest are composed of source or libraries that presently fail to build on Windows (x86 also).

Are you actually using them?

We could maybe just skip some of the broken files instead of the libraries they are in.
You know, the klex, ktok, kyacc probably used to work and probably don't use the broken stuff.

Surely we have the much lesser evil here though.

 - Jay

________________________________

**Comment by VictorMiasnikov** [comment]
> Lots of code in there that doesn't compile on Windows.

 +

> rest are composed of source or libraries that presently fail to build on Windows 

 But I succeful compiled this files (  klex, ktok, kyacc ) before #50 

After #50 I have problems

**Comment by jaykrell** [comment]
I had errors all around here.
Here I am starting to kinda fix it.
https://github.com/modula3/cm3/pull/55/files#r289439680

**Comment by VictorMiasnikov** [comment]
Hi!I think this:(OS_TYPE, "WIN32")affected both "M-3 for Win 32bit"and "M-3 for Win 64bit"I "tested"  ( run "upgrade distrib" script)only AMD64_NT variant ( with VC110 )If You can disable only "M-3 for Win 32bit"-- this will be welcomed  Thanks!Best regards, Victor Miasnikov31.05.2019, 18:31, "Jay Krell" <notifications@github.com>:I had errors all around here.
Here I am starting to kinda fix it.
https://github.com/modula3/cm3/pull/55/files#r289439680

**Comment by jaykrell** [comment]
I reverted the change and “fixed” stuff.
Mika please review. I still can’t quite build.

**Comment by jaykrell** [comment]
Affecting AMD64_NT was deliberate. The caltech code also would not compile there.

- Jay
________________________________

**Comment by VictorMiasnikov** [comment]
Hi!I'm big sorry : in fact my "sub-issue"  happend"after 2019-01-17" or even aftet 2018-11-XX(I see that You have worked AMD64_NT .Wich version of MS Visual Studio based?I have problems with MS VS 2017 downloaded 2019-01-17I continue using MS Visual Studio 2012)Best regards, Victor Miasnikov 02.06.2019, 04:02, "Jay Krell" <notifications@github.com>:Affecting AMD64_NT was deliberate. The caltech code also would not compile there.

- Jay
________________________________

**Comment by jaykrell** [comment]
I’m using 2019 or maybe 2017.
What specific problems?
Definitely exception handling was broken & I fixed it. Broken for I think 2015 and newer.

- Jay
________________________________

**Comment by VictorMiasnikov** [comment]
Hi!(Sorry for style, possibly orfo, etc. I write on my mobile phone )> Definitely exception handling was broken & I fixed it. I'm don't remember it has published in #47 topic ... Or it doesn't publish ...Ok: please 1) Send me ( and D.M.) correlated GitHub URLof source code 2) public  ( as minimum for me and D.M.) binary distributive of Modula-3 for Windows( of course with _worked_ mklib.exe., i.e. "all" variant  ( "min" has broken since 2015-XX ) )(> What specific problems?With VS 2012 I has good cm3.exe .With VS 2017 even "cm3 --help" doesn't work.   )Best regards, Victor Miasnikov 02.06.2019, 09:37, "Jay Krell" <notifications@github.com>:I’m using 2019 or maybe 2017.
What specific problems?
Definitely exception handling was broken & I fixed it. Broken for I think 2015 and newer.

- Jay
________________________________

**Comment by jaykrell** [comment]
Amd64_nt distribution i can make very soon. I have to check where we can put files.
Nt386 should get a fix first

- Jay
________________________________

**Pull request merged**
