### PR TITLE
m3c: Allow invalid IR: direct calls with insufficient parameters

### PR DESCRIPTION
**Pull request by jaykrell**
m3front is willing to issue an unconditional abort in the middle of start_call/call.
Upon which, it stops popping parameters.

This leads to errors from the C compiler, for calls with insufficient parameters.

Test p268 does this.

When we see this, evaluate whatever parameters we get, possibly before the abort, maybe that has visible
side effects, but skip the call.

Now p268 compiles.

Note that indirect calls in m3c are presently untyped.
This should apply there as well, but the C compiler would already accept what we had.

This assumes no continue after abort, which is a little debatable.
But we don't have enough parameters from m3front so we cannot very
well make the call. m3front ignores that you can continue from
faults in a debugger.

We should probably make this conditional on if we saw all the parameters.

We should probably expect better IR from m3front also.

And really m3front should just reject this code with an error.

### CODE REVIEW

**Comment by mikanystrom** [comment]
I think the best thing for abort (ASSERT FALSE) to do in M3 is to raise a
RuntimeError.E exception.  My Scheme interpreter does catch a number of
runtime issues using that mechanism.  With the gcc backend, some runtime
errors are mapped to the exception, and others are not...

**Comment by jaykrell** [comment]
It calls RTHook.ReportFault.

C:\s\cm3\m3-libs\m3core\src\runtime\common\RTHooks.m3(93):PROCEDURE ReportFault (module: ADDRESS(*RT0.ModulePtr*);  info: INTEGER)
     RTException.Raise (a);
C:\s\cm3\m3-sys\m3back\src\M3x86.m3(3451):          reportfault(u, code);
C:\s\cm3\m3-sys\m3back\src\M3C.m3(6358):    reportfault(self, code);
etc.

Do you consider these continuable?
I can continue past them in a debugger at least.
I think you can catch them even.

But m3front ends up issuing kinda nonsense.
It'll be popping parameters, then decide a parameter is invalid, won't pop it, and issue a fault.
Leading to insufficient parameters for the function call in progress, which the C compiler rightfully rejects.
I suspect this is recently changed behavior, and/or only occurs in test code.

 - Jay

________________________________

**Comment by jaykrell** [comment]
To be clear, I'd rather reject these programs.
In either case I don't think the IR should be considered valid.
Does LLVM accept it?

 - Jay

________________________________

**Comment by mikanystrom** [comment]
Not really continuable but at least catchable. Not everything that is
catchable is really implemented right in the standard cm3 today.

**Pull request merged**
