### PR TITLE
AMD64_LINUX - build with -no-pie

### PR DESCRIPTION
**Pull request by VictorMiasnikov**
Tested on Debian 10.8.0 amd64 with m3gdb builded on Debian 8.11.1 amd64

### CODE REVIEW

**Comment by VictorMiasnikov** [comment]
This is first step to going to this: https://github.com/modula3/cm3/pull/634#issuecomment-862177948
 ( or like this)

**Comment by jaykrell** [comment]
Position independent is more secure. We should not turn it off.

**Comment by jaykrell** [comment]
Use a newer debugger. Don't fork old debuggers.

**Comment by VictorMiasnikov** [comment]
} Position independent is more secure. We should not turn it off.

"Position independent" can be used with m3gdb?

**Comment by VictorMiasnikov** [comment]
} Use a newer debugger

 This:

https://github.com/VictorMiasnikov/cm3/releases/download/d5.11.9-ZZYYXX-20220208_13-48/cm3-bin-m3gdb-AMD64_LINUX-d5.11.9-AMD64_LINUX.Debian_11.3.0-1_and_.GCC_11.3.0.-2022-02-08_13-48__FIXed__by__VVM__2022-05-18_14-06__AMD64_LINUX__Target__cm3-3be819e__m3gdb.tar.xz

 from
https://github.com/VictorMiasnikov/cm3/releases/tag/d5.11.9-ZZYYXX-20220208_13-48

is "a newer debugger" ?

**Comment by jaykrell** [comment]
I am sorry but there is no good answer here.
Forking gdb years ago and never updating puts Modula-3 in a bad position for multiple reasons.
PIE is totally normal and good and "should" not be a problem.
Windows has been using PIE by default for over 15 years and optionally prior.
It just should not be a big deal.
I realize it is a problem though.
"Newer debugger" would be updating Modula-3's gdb fork, or not relying on forking gdb at all.

**Comment by VictorMiasnikov** [comment]
} I am sorry but there is no good answer here.
I see...

One second...

**Comment by VictorMiasnikov** [comment]
I create release named "d5.11.9-ZZYYXX-20220208_13-48"

https://github.com/VictorMiasnikov/cm3/releases/tag/d5.11.9-ZZYYXX-20220208_13-48

 File

cm3-all_with_m3llvm-AMD64_LINUX-d5.11.9-AMD64_LINUX(Debian_11.3.0-1_and_{{GCC_11.3.0}})-2022-02-08_13-48__FIXed__by__VVM__2022-05-18_14-06__AMD64_LINUX__Target__cm3-3be819e.deb

contain

```
═ ...__by__VVM__2022-05-18_14-06__AMD64_LINUX__Target__cm3-3be819e.deb _ Step 0.dir\usr--local--cm3\bin ═
w                                      Name                                        │ Size │  Date  │Time
..                                                                                 │  Up  │20.05.22│18:45
config                                                                             │Folder│18.05.22│12:06
m3llvm                                                                             │2325 K│20.05.22│18:45

═ ...__by__VVM__2022-05-18_14-06__AMD64_LINUX__Target__cm3-3be819e.deb _ Step 0.dir\usr--local--cm3\pkg ═
w                                      Name                                        │ Size │  Date  │Time
..                                                                                 │  Up  │20.05.22│18:45
llvm13                                                                             │Folder│20.05.22│18:45
llvm13bindings                                                                     │Folder│20.05.22│17:33


```

Binary compiled with "llvm13bindings style" may be can be debugged this "LLVM Debugger".

But before this we should use m3gdb.

**Pull request closed without merging**
