### PR TITLE
Remove cvsup from build due to MD5 library collision with libm3.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by hosking** [comment]
I'm not sure I understand the issue...

**Comment by jaykrell** [comment]
Cvsup  has long has interface md5.
Llbm3 recently gained interface md5.
So now cvsup fails to build.
Probably libm3's new interface should be renamed, but probably nobody needs cvsup.
Probably we should see if there some free CI we can setu (Hudson, Travis, Jenkins..).

**Comment by RodneyBates** [comment]
Any problem with just removing the MD5 source code from cvsup and just letting
cvsup get MD5 out of libm3?  I'm sure cvsup must already be using libm3.
Or are the two MD5s different?  If so, I would advocate renaming the
version in cvsup, which is probably little used now, and keeping the
obvious name for the version in libm3.

Was there already some other problem with cvsup not building?

**Comment by jaykrell** [comment]
I kinda think language/builder should handle this. Cvsup’s md5 should be considered local, as long as cvsup doesn’t depend in libm3’s md5 directly or indirectly.

**Comment by mikanystrom** [comment]
The two MD5s are fairly different.

In my local copy, I renamed the MD5 in suplib to SupMD5, to keep the two
names from colliding.  It's only a few lines of code to change here and
there.

But I still had to disable cvsup from my build because I was getting linker
errors.

Can someone show me how to put the diff above in for review?  I am not a
git master.

     Mika

**Pull request merged**
