### PR TITLE
RCC_upgradeCM3_Win10_Fix

### PR DESCRIPTION
**Pull request by VictorMiasnikov**
RCC_upgradeCM3_Win10_Fix

### CODE REVIEW

**Comment by VictorMiasnikov** [comment]
```

jaykrell commented yesterday
{{{
I'd really prefer to delete all the .cmd and .sh files.
}}}



 VictorMiasnikov commented yesterday • 
{{{
JK} 29.04.2021, 07:56, "Jay Krell"
JK} I'd really prefer to delete all the .cmd and .sh files.

I use both .py and .cmd
And need every time apply this patches in non-automatic mode.

- - -

 With .py we have "Phyton2 to Phyton3" upgrade problem, etc.

- - -

 Please, don't kill anything.
And Cygwin too -)
}}}

```

**Comment by jaykrell** [comment]
There is no Python2/3 problem. Just use Python2.
True, the incompatibility of Python3 is one of a few reasons to drop Python.
But .cmd should really never be used. It is the worst possible answer to any question.
Eventually m3makefile should be able to traverse packages, rendering these scripts fairly redundant.

**Comment by VictorMiasnikov** [comment]
> Just use Python2.

for build LLVM need Python3

> True, the incompatibility of Python3 is one of a few reasons to drop Python.

I ask for _repair_ some .cmd scripts.
I don't ask kill or drop .py scripts.

> It is the worst possible answer to any question.

I need I can open 3 .. 7 Issue about bad and unstable behavior of .py scripts.

**Comment by VictorMiasnikov** [comment]
Please, _apply_ this super simply and even trivial patches.

 I want sent patches related LLVM as backend of Modula-3.
But have some risks related my "GUI GIT Client"

**Comment by VictorMiasnikov** [comment]
> Eventually m3makefile should be able to traverse packages, rendering these scripts fairly redundant.
 
  There is a ritoric question:
*.md and *.txt must be killed too?..

**Comment by jaykrell** [comment]
Please do open any issues about the .py files. I use them all the time, on Mac, Windows, and Linux.

**Comment by jaykrell** [comment]
Whatever changes to .cmd files are fine with me. I never use them. I would prefer to see them and .sh deleted.

**Comment by VictorMiasnikov** [comment]
No problem.06.05.2021, 00:51, "Jay Krell" ***@***.***>:
Please do open any issues about the .py files. I use them all the time, on Mac, Windows, and Linux.

**Comment by VictorMiasnikov** [comment]
Fine =} press applyI use .cmd in case .py doesn't work as need06.05.2021, 00:51, "Jay Krell" ***@***.***>:
Whatever changes to .cmd files are fine with me. I never use them. I would prefer to see them and .sh deleted.

**Comment by jaykrell** [comment]
For Python2 to be 1GB is unfortunate, agreed...but it is "only" 100MB for me. or 250ish..

 \treesize \Python27
treesize: \Python27, 96.99 MB in 6,818 files, 177 directories

\treesize \Python39
treesize: \Python39, 259.66 MB in 9,954 files, 448 directories

**Comment by VictorMiasnikov** [comment]
===
I see

Commits on May 6, 2021
LLVM and Windows amd64 related improvements. (#415) …

```
@jaykrell
@VictorMiasnikov
jaykrell and VictorMiasnikov committed 41 seconds ago
```

Thank!
==


But doesn't see this path set ( yet)

**Comment by VictorMiasnikov** [comment]
```
Commits on May 6, 2021
scripts: Update some .cmd files for Windows 10. (#416) …

@jaykrell
@VictorMiasnikov
jaykrell and VictorMiasnikov committed 1 minute ago

```

**Comment by VictorMiasnikov** [comment]
I see:
```
Commits on May 6, 2021
scripts: Update some .cmd files for Windows 10. (#416) …

@jaykrell
@VictorMiasnikov
jaykrell and VictorMiasnikov committed 1 minute ago

```

Thank!

**Pull request merged**
