### PR TITLE
caltech-bool: Convert to valid C++.

### PR DESCRIPTION
**Pull request by jaykrell**
- Add extern "C".
 - Rename true and false to True and False.

### CODE REVIEW

**Comment by mikanystrom-intel** [comment]
wait.... is it a rule that c_source must be valid C++?

That's a pretty big restriction.  I am not entirely comfortable with it.

**Comment by mikanystrom** [comment]
Hi Jay,

I have a feeling if you convert all existing C code from C to C++, it will
break a lot of compile flows.  c_source is C source.  It's not C++!

I recall cleaning up some of this a few years ago (but maybe you think I
dirtied things...)

There's cxx_source in the m3makefiles if you want to have C++.

On Linux, the way at least I have it set up is:

c_source is C -- it uses gcc to compile
cxx_source is C++ -- it uses g++ to compile
g++ is used for linking, always.

I think if you start checking in C++ as c_source, or start requiring that
c_source be actual C++, a lot of things will break.  Plus you will
introduce a lot of incompatibilities.  I don't know about others, but I
have code generators that generate C as well.  f2c also generates C, if you
have Fortran 77 to compile (although I've been using ifort and checking in
the assembly as you can see, and specialized it for AMD64_LINUX, _FREEBSD).

     Mika

**Comment by jaykrell** [comment]
Yeah I knew there'd be complaints.
Is `cxx_source` what we agreed?

But it isn't bad as it sounds, imho.
First of all, all the C code in the tree is now valid C++.
I had already done that before the additional caltech stuff.
The additional caltech stuff was no big deal.

I believe the AMD64_LINUX config files were "fixed" to compile as C.
But others like I386_LINUX not so. Which is what I was building.
I guess we can fix that, and introduce cxx_source, but it was easy to do it this way. At least for this code.
I'm making no claims about the vast swaths of Modula-3 + C codebases out there.

The config files have been this way for a long time, but you can change them back.

I would like the C backend to generate C++, for optimized exception handling, but it is a long ways out, or never.
And I guess cxx_source will precede that. Or something.

And I'm not worried about incompatibilities.
I know both languages very well and have converted stuff in both directions.
If it compiles in both, then it has the same meaning in both, except for extern "C".
If you have specific examples of a compatibility concern please speak up.

**Comment by jaykrell** [comment]
"or something": I mean, C backend generating C++ does not require a beautiful public working `cxx_source`. It can some custom quake dedicated to the C backend, though in reality, `c_source` would be factored with C backend quake upon a common case.

**Comment by jaykrell** [comment]
Oh and yeah yeah:

void f();

does not have the same meaning in C and C++.
in C, it means accepts any parameters, in C++ it means accepts no parameters.

For any parameters in C++, write void f(...), which isn't valid C.
For no parameters in either language, write void f(void);
So you are left with if __cplusplus for that very unusual construct.

**Comment by mikanystrom** [comment]
My concern is just to know what it is OK to check in and what is not.

If it's pretty obvious how to code such that c_source will compile with a C
compiler and whatever else you need, I guess that is OK.  #ifdef magic I
take it...

**Comment by mikanystrom** [comment]
Sure, I don't think we need to accept K&R code.

**Comment by jaykrell** [comment]
Let's try a polite friendly experiment?
You checkin C code, I convert it to C++?
Or yeah, get `cxx_source` into master, for all platforms..convert most/all the existing c_source to cxx_source, maybe undo the caltech changes so we have any c_source, and then keep using both and I'll do less boring stuff. :)

**Comment by mikanystrom** [comment]
Let me pull your stuff and see what happens.  I don't want to make
pointless work for you, either.

**Comment by jaykrell** [comment]
I don't mind convert code to C++. I confirms my world view.
Keep checking in C. :)

What I'm being less quick to do is revise the quake to support cxx_source but I guess that is super trivial, really.

The C++ decision is actually hurting me at the moment, because it turns:
char *x;
setjmp(x)

from a warning in C to an error in C++. I need to compile the C backend output as C, or make some fix here..
That's why today's Linux releases are gcc-based. :)

**Pull request merged**
