### PR TITLE
merge my branch to master

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by hosking** [comment]
Hi Jay,

I'm not quite sure what you are trying to do.

**Comment by jaykrell** [comment]
I don't think I have write access.

 - Jay

**Comment by hosking** [comment]
I'm pretty sure you do. Did you authenticate?

**Comment by jaykrell** [comment]
Yes and no.I can push to my own github fork.Sometimes but not always I get repeated password requests.Some ssh key got automatically added.And then later I added another.
Maybe I should start over again.
 - Jay



Date: Wed, 18 Mar 2015 09:59:23 -0700

**Comment by hosking** [comment]
If you clone via ssh you should be able to push too.

**Comment by jaykrell** [comment]
ah -- not git clone copy/pasted url from the github web page?That could explain it.I'll try again later.
Thanks, - Jay



Date: Wed, 18 Mar 2015 10:52:59 -0700

**Comment by jaykrell** [comment]
no luck.
With ssh:
 
C:\dev2\cm3>git push origin master -v
Pushing to git@github.com:modula3/cm3.git
ERROR: Permission to modula3/cm3.git denied to jaykrell.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

 
jaykrell
or jay.krell@cornell.edu
or Jay Krell?
or no matter?
 
   - Jay



 
From: jay.krell@cornell.edu
To: reply@reply.github.com; cm3@noreply.github.com
Subject: RE: [cm3] merge my branch to master (#2)
Date: Wed, 18 Mar 2015 18:03:40 +0000




ah -- not git clone copy/pasted url from the github web page?That could explain it.I'll try again later.
Thanks, - Jay



Date: Wed, 18 Mar 2015 10:52:59 -0700

**Comment by jaykrell** [comment]
Ok, sorry, it is working now. Either you just added me, or my accepting the invitation to join the organization made it work.
 
Thanks,
 - Jay


From: jay.krell@cornell.edu
To: reply@reply.github.com; cm3@noreply.github.com
Subject: RE: [cm3] merge my branch to master (#2)
Date: Fri, 20 Mar 2015 10:57:18 +0000




no luck.
With ssh:
 
C:\dev2\cm3>git push origin master -v
Pushing to git@github.com:modula3/cm3.git
ERROR: Permission to modula3/cm3.git denied to jaykrell.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

 
jaykrell
or jay.krell@cornell.edu
or Jay Krell?
or no matter?
 
   - Jay



 
From: jay.krell@cornell.edu
To: reply@reply.github.com; cm3@noreply.github.com
Subject: RE: [cm3] merge my branch to master (#2)
Date: Wed, 18 Mar 2015 18:03:40 +0000




ah -- not git clone copy/pasted url from the github web page?That could explain it.I'll try again later.
Thanks, - Jay



Date: Wed, 18 Mar 2015 10:52:59 -0700

**Comment by hosking** [comment]
Sent from my iPad

> On Mar 20, 2015, at 7:07 AM, jaykrell <notifications@github.com> wrote:
> 
> Ok, sorry, it is working now. Either you just added me, or my accepting the invitation to join the organization made it work.

The latter!

> 
> Thanks,
> - Jay
> 
> 
> From: jay.krell@cornell.edu
> To: reply@reply.github.com; cm3@noreply.github.com
> Subject: RE: [cm3] merge my branch to master (#2)
> Date: Fri, 20 Mar 2015 10:57:18 +0000
> 
> 
> 
> 
> no luck.
> With ssh:
> 
> C:\dev2\cm3>git push origin master -v
> Pushing to git@github.com:modula3/cm3.git
> ERROR: Permission to modula3/cm3.git denied to jaykrell.
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.
> 
> 
> jaykrell
> or jay.krell@cornell.edu
> or Jay Krell?
> or no matter?
> 
> - Jay
> 
> 
> 
> 
> From: jay.krell@cornell.edu
> To: reply@reply.github.com; cm3@noreply.github.com
> Subject: RE: [cm3] merge my branch to master (#2)
> Date: Wed, 18 Mar 2015 18:03:40 +0000
> 
> 
> 
> 
> ah -- not git clone copy/pasted url from the github web page?That could explain it.I'll try again later.
> Thanks, - Jay
> 
> 
> 
> Date: Wed, 18 Mar 2015 10:52:59 -0700
> From: notifications@github.com
> To: cm3@noreply.github.com
> CC: jay.krell@cornell.edu
> Subject: Re: [cm3] merge my branch to master (#2)
> 
> If you clone via ssh you should be able to push too.
> 
> 
> 
> Sent from my iPad
> 
> 
>

**Pull request merged**
